### ISSUE TITLE
Functional requirements

### ISSUE THREAD

**Issue by JZZZ1314** [Haoming02/comfyui-floodgate#1]
I want to know if it's possible to customize options instead of just switching options?
For example, I can choose controlnet or ipadapter or more other possibilities, and I can make work choices in the node section

**Comment by Haoming02** [comment]
I'll need to research on how to make Nodes that can take connection of Type.
Otherwise, it will basically need a different node for every single Type of connection...

**Comment by cardenluo** [comment]
Nowadays, the switching nodes of many plug-ins are limited to input switching. Output switching, this is a great idea. It would be so convenient if  switch any output like here.
![image](https://github.com/Haoming02/comfyui-floodgate/assets/133877069/d01fa4b0-553c-420b-a42b-1f9c62f29c85)
