### ISSUE TITLE
switch is invalid when chage gate_open fromt input to wiget

### ISSUE THREAD

**Issue by 6sixteen** [Haoming02/comfyui-floodgate#2]
When I chage gate_open from input to wiget, and add the Boolean Input, the floodGate always execute the open flow.
![image](https://github.com/Haoming02/comfyui-floodgate/assets/26003677/a4c07599-4f8c-4014-b9ec-243ed45fd0d6)

**Comment by 6sixteen** [comment]
i found.
`gate_open = prompt[ID]['inputs']['gate_open']`

> if I add a new node to input Boolean, gate_open will be ["20",0] （node id and parameter location）
> I should chang ["20",0] to Boolean

`prompt = block_gate(prompt, ID, gate_open)`

That's all.

**Comment by Haoming02** [comment]
Using the `Primitive` node works for me

![image](https://github.com/Haoming02/comfyui-floodgate/assets/73768377/20f019d2-ea69-497e-ab4c-f4cbfa598f2c)

**Comment by Haoming02** [comment]
But yeah, I will add the function to grab the boolean value from connection

**Comment by Haoming02** [comment]
That node should also work now

**Comment by 6sixteen** [comment]
Thanks. 
`# in def hijack_validate(prompt)`
`gate_open = prompt[ID]['inputs']['gate_open']`
`if isinstance(gate_open, list):`
 `  gate_open = get_boolean_from_node(prompt,gate_open)`
 `prompt = block_gate(prompt, ID, gate_open)`
 
`def get_boolean_from_node(prompt,gate_open):`
` boolean_node = prompt[gate_open[0]]`
` boolean_node_object = nodes.NODE_CLASS_MAPPINGS[boolean_node['class_type']]()`
` method = getattr(boolean_node_object,boolean_node_object.FUNCTION)`
` res = method(**boolean_node["inputs"])`
` # just return original value`
` return res[gate_open[1]]`

This is my implementation.
