### ISSUE TITLE
Only primitive boolean alowed

### ISSUE THREAD

**Issue by villain535** [Haoming02/comfyui-floodgate#3]
FloodGate accepts only primitive boolean. How to fors it accept boolean from another nodes?

![photo_2024-03-01_18-57-08](https://github.com/Haoming02/comfyui-floodgate/assets/12443208/76f36770-472f-4753-afe3-19c8f0c4ac8f)

**Comment by Haoming02** [comment]
> **Note:** The logic flow is parsed during the queuing stage, not the execution stage. As a result, the boolean value has to be already determined when you press Queue Prompt, such as from the toggle or a primitive node. If you use a node that outputs a boolean during execution, this will not work.

You can't.
